name: macOS

on:
name: macOS

on:
  push:

jobs:
  install:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yadm and clone dotfiles
        run: |
          curl -fsSL https://github.com/yadm-dev/yadm/raw/master/yadm -o /usr/local/bin/yadm
          chmod +x /usr/local/bin/yadm
          yadm clone https://github.com/kyooo8/dotfiles.git --bootstrap

      - name: Check Neovim setup
        run: |
          nvim -E -s <<'EOF'
          :source $HOME/.config/nvim/init.lua
          :Lazy install
          :Lazy health
          :qa
          EOF

